language: python
python:
    - "3.3"
    - "3.4"
install:
    - travis_retry pip install -r requirements.txt
    - travis_retry python setup.py install
script:
  - coverage run --source=open_weather_forecast setup.py test
after_success:
  - coveralls